package com.fitpeo.assignment;

import static org.testng.Assert.assertEquals;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.testng.Assert;
import org.testng.annotations.Test;

public class TC_RevenueCaliculatorTest_001 extends BaseClass{
	
@SuppressWarnings("deprecation")
@Test(priority=1)	
public void RevenueTest() throws InterruptedException {
		
		driver.get(baseUrl);
		driver.manage().window().maximize();
		WebElement RevenueCaliculator = driver.findElement(By.xpath("//a[@href='/revenue-calculator']"));
		RevenueCaliculator.click();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
}
@Test(priority=2)	

public void SliderTest() throws InterruptedException {
	
	WebElement Slider = driver.findElement(By.xpath("//div[@class='MuiBox-root css-j7qwjs']/span[1]/span[3]"));
	Actions act=new Actions(driver);
	act.dragAndDropBy(Slider, 94, 0).perform();
	WebElement Sliderval = driver.findElement(By.xpath("//div[@class='MuiBox-root css-j7qwjs']/div/div/input"));
	System.out.println(Sliderval.getAttribute("value"));
	Sliderval.click();
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	Sliderval.sendKeys(Keys.ARROW_DOWN);
	System.out.println(Sliderval.getAttribute("value"));
	Thread.sleep(5000);
	WebElement getvalue1=driver.findElement(By.xpath("//div[@class='MuiBox-root css-1pr1g5o']/div[2]/p[2]"));
	Assert.assertEquals(getvalue1.getText(),Sliderval.getAttribute("value"));
}
@Test(priority=3)
public void checkboxTest() throws InterruptedException {
	WebElement checkbox1=driver.findElement(By.xpath("//div[@class='MuiBox-root css-1p19z09']/div[1]//input"));
	checkbox1.click();
	WebElement checkbox2=driver.findElement(By.xpath("//div[@class='MuiBox-root css-1p19z09']/div[2]//input"));
	checkbox2.click();
	WebElement checkbox3=driver.findElement(By.xpath("//div[@class='MuiBox-root css-1p19z09']/div[3]//input"));
	checkbox3.click();
	WebElement checkbox4=driver.findElement(By.xpath("//div[@class='MuiBox-root css-1p19z09']/div[8]//input"));
	checkbox4.click();
	WebElement reimbursement=driver.findElement(By.xpath("//div[@class='MuiBox-root css-rfiegf']/header/div/p[4]/p"));
	Assert.assertEquals(reimbursement.getText(),"$75600");
}
}